### ISSUE TITLE
@active_if on runHumann3_metaranscritpome

### ISSUE THREAD

**Issue by schyen** [OxfordCMS/OCMS_Shotgun#17]
I'm considering adding a `@active_if` decorator in from of `runHumann3_metatranscriptome` so it doesn't create at `humann3_mtx.dir` when there is no metatranscriptome data. However I'm wondering if that will cause problems on the `mergeHumannOutput` task which uses `@collate([runHumann3, runHumann3_metatranscriptome])` 

On a related note, would `@collate([runHumann3, runHumann3_metatranscriptome])` merge `pathcoverage` (and respective humann3 output files) files across both metagenome and metatranscriptome datasets? I think that would be problematic. I'm not really familiar with how collate works.

**Comment by jethrojohnson** [comment]
I would suggest using the same conditional as for poolTranscriptomeFastqs (@active_if(PARAMS['location_transcriptome'])). 

This won't cause any issues downstream - runHumann3_metatranscriptome is already rendered inactive by the @active_if decorator on the preceding pipeline step. All you will be doing differently is inactivating the mkdir() command. 

To your second point, the output of @collate is determined by the two captured groups in the regex statement:  group(1) directs metagenome and metatranscriptome to different output directories, group(2) directs pathcoverage|pathabundance|genefamilies files to different output files within those directories... hence the output will not be merged.

**Comment by schyen** [comment]
perfect. thanks for the explanation :) I'll add the conditional.
