### ISSUE TITLE
cgat combine_tables is deprecated

### ISSUE THREAD

**Issue by HollyRoach** [OxfordCMS/OCMS_Shotgun#19]
Within ocmsshotgun/pipeline_preprocess.py the cgat-app tool combine_tables is called within two functions: combineRNAClassification and collateReadCounts.

However, this tool has now been [deprecated](https://github.com/cgat-developers/cgat-apps/blob/master/deprecated_scripts.md?plain=1).

**Comment by nickilott** [comment]
It looks like we should change everything to ```cgat tables2table``` - we should just be able to substitute out combine_tables. In my cgat-apps installation I have both tables2table and combine_tables so it should even be backwards compatible for most people

**Comment by nickilott** [comment]
I am closing this now as it appears to work in pipeline_preprocess - kraken2 still needs to be checked but will open another issue if it's a problem.
