### ISSUE TITLE
bmtagger.sh issues

### ISSUE THREAD

**Issue by nickilott** [OxfordCMS/OCMS_Shotgun#24]
Hi,

So @HollyRoach had identified a few issues with bmtagger - it's calls to srprism were somewhat messed up and using arguments that didn't exists. Doing some more investigations it is also apparent that it is not reading the srprismopts correctly and so was throwing additional errors.

We now have a bmtagger_mod.sh that fixes these bugs as it is actually quite difficult to track down where to submit issues to - this is part of the reason for the discussion around switching to bowtie for host read removal...

**Comment by HollyRoach** [comment]
Do we need to update ocmsshotgun/modules/PreProcess.py so that the statements are calling bmtagger_mod.sh rather than bmtagger.sh?

**Comment by nickilott** [comment]
Yes so I am in the process of doing this now and fixing the combine_tables issues :) will let you know when the cahnges have been merged in
